### ISSUE TITLE
Pulsar and Nova Splunk returners send host info differently

### ISSUE THREAD

**Issue by mew1033** [HubbleStack/Quasar#22]
Pulsar uses the fqdn grain and nova uses the minion id. We need to decide which one to use and make sure it's consistent.

**Comment by basepi** [comment]
Let's standardize on the minion ID. FQDN can be wrong if the hostname is misconfigured on the box, but minion ID is almost certainly useful, and definitely unique across a given master.

**Comment by basepi** [comment]
Fixed by #34
