### ISSUE TITLE
Remove returners which are identical to those shipped with salt

### ISSUE THREAD

**Issue by basepi** [HubbleStack/Quasar#5]
We should only host returners here that are specialized in some way for hubble. Otherwise we have to maintain and update them. We're much better off just using the returners that ship with salt, because they get bugfixes.

Thoughts?

**Comment by cedwards** [comment]
Let's do it.

**Comment by cedwards** [comment]
what do we call them? `nova_splunk` and `nebula_splunk` or...?

**Comment by basepi** [comment]
I think I prefer the `splunk` as a prefix, not a suffix.

**Comment by basepi** [comment]
I think they're fine the way they are for now.
